### ISSUE TITLE
dirq deprecation

### ISSUE THREAD

**Issue by rptaylor** [rptaylor/kapel#51]
dirq might be getting deprecated (? unclear). 
Ways to add files to output without dirq are described here: https://github.com/apel/ssm/tree/dev?tab=readme-ov-file#adding-files

The programmatic option would be to use this python module:  https://github.com/apel/ssm/blob/dev/ssm/message_directory.py

**Comment by rptaylor** [comment]
Julia Andreeva says "dirq is used by APEL client and therefore , we will find a way to continue to support it."

So should be okay for now.

**Comment by tofu-rocketry** [comment]
The message directory module can be used by changing SSM's config for sending messages, but we didn't add an option for receiving. This was because, while we wanted to simplify sending messages for certain use-cases, we preferring the well-tested reliability of dirq for receiving at the server end where we receive _a lot_ of messages.

We'll see how the CERN support for dirq goes, and I guess `message_directory` could be used as a fall back for receiving if needed.
